version: "3.7"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: opencv_api
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    env_file:
      - .env
  web:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    environment:
    - CHOKIDAR_USEPOLLING=true
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8085:80